### ISSUE TITLE
[FE] Redwood app should hot reload when /packages is modified

### ISSUE THREAD

**Issue by jahabeebs** [pi0neerpat/oauth2-server-redwood#21]
Builds on #19 

Currently we have a build:watch script in the repo root that will re-build `/packages` when a file is modified there, but the app won't be reloaded to include these changes and instead `yarn rw dev` will be re-run to reload the new build. The Redwood app should support hot reloading to files in `/packages` without having to re-run `yarn rw dev`.

**Comment by pi0neerpat** [comment]
Closing as stale
