### ISSUE TITLE
Jose package - security 

### ISSUE THREAD

**Issue by pi0neerpat** [pi0neerpat/oauth2-server-redwood#34]
This is a continuation of #33

Using the releases, or other relevant sources, please check if there were any important security updates between the version we use, and the latest.

**Comment by jahabeebs** [comment]
@pi0neerpat the entire Keystore object was removed in 3.0.0 (the version that's right after the one we're using--2.0.6) and the release note says "no dependencies, browser support, support for verification using a remote JWKS endpoint"...can't find an explanation as to why it was removed but this is the commit: https://github.com/panva/jose/commit/357fe0b964903e8c84ab49f0f27ddf0447d44c84 and this is where the release notes are: https://github.com/panva/jose/releases?page=12

seems like according to the docs this is the new way to generate jwks locally?: https://github.com/panva/jose/blob/main/docs/functions/jwks_local.createLocalJWKSet.md

I did an npm audit and it didn't note any vulnerabilities. I looked through all the release note individually and in 3.3.0 there was "reject JWTs with b64:": "https://github.com/panva/jose/commit/691b44ad4717c82a06539facfedff48fa0e9c6a9. I guess previously JWTs could use an unencoded payload?

In 3.14.4 there were some bug fixes to throw JWEInvalid JWS/Invalid when jwe/jws protected header is invalid: https://github.com/panva/jose/releases?expanded=true&page=8&q=

none of the above fixes in the release notes were mentioned as security vulnerabilities

there was previously a security vulnerability in versions lower than ours but ours has the patch: https://github.com/advisories/GHSA-jv3g-j58f-9mq9

**Comment by pi0neerpat** [comment]
- looking at release history :+1: 
- npm audit :star: 
- Finding the new method for generating jwks :1st_place_medal: 

Amazing. Thank you! I'll make an issue to update to the latest method, and leave that open to the public
